language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

cache:
  directories:
    - $HOME/.composer/cache/files

stages:
  - Code Style
  - Test

jobs:
  include:
    - name: Code Style
      php: 7.1
      install: composer install --ignore-platform-reqs
      addons: skip
      script: vendor/bin/php-cs-fixer fix --using-cache=no --verbose --dry-run

install:
  - git clone --branch=release https://github.com/krakjoe/ui
  - cd ui
  - mkdir -p deps/{lib,include}
  - git clone --depth=1 https://github.com/andlabs/libui
  - cd libui
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - cp out/libui.* ../../deps/lib
  - cp ../ui*.h ../../deps/include
  - cd ../..
  - phpize
  - ./configure --with-ui=deps
  - make
  - cd ..
  - echo "extension=ui.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - make vendor/autoload.php
