language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

#addons:
#  apt:
#    packages:
#      - libgtk-3-dev

cache:
  directories:
    - $HOME/.composer/cache/files

stages:
  - code style
  - test

jobs:
  include:
    - stage: code style
      php: 7.1
      install: composer install --ignore-platform-reqs
      addons: skip
      script: vendor/bin/php-cs-fixer fix --using-cache=no --verbose --dry-run

install:
  - ./travis/install-ui.sh
  - make vendor/autoload.php
