language: php

php:
  - 7.1
  - 7.2
  - nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

install:
  - git clone --branch=release https://github.com/krakjoe/ui
  - cd ui
  - git checkout a7020afbb6d5c948c25021329277f849ee4610f6
  - mkdir deps
  - mkdir deps/lib
  - mkdir deps/include
  - git clone --depth=1 https://github.com/andlabs/libui
  - cd libui
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - cp out/libui.* ../../deps/lib
  - cp ../ui*.h ../../deps/include
  - cd ../..
  - phpize
  - ./configure --with-ui=deps
  - make
  - cd ..
  - echo "extension=ui.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - make vendor/autoload.php
