language: php

php:
  - 7.1
  - 7.2
  - nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

install:
  - git clone --depth=1 https://github.com/andlabs/libui
  - cd libui
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - cp out/libui.* /usr/local/lib
  - cp ../ui*.h /usr/local/include
  - cd ../..
  - pecl install ui-2.0.0
  - make vendor/autoload.php
