language: php

php: 7.1
# Below is all commented out because cannot be built atm
#  - 7.2
#  - nightly

#matrix:
#  allow_failures:
#    - php:
#      - 7.2
#      - nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/Library/Caches/Homebrew

install:
  - ./travis/install-ui.sh

matrix:
  include:
    - os: linux
    - os: osx
      language: generic
      addons: skip
      before_install:
        - brew update
        - brew install php71
        - export PATH="/usr/local/opt/php@7.1/bin:$PATH"
        - export PATH="/usr/local/opt/php@7.1/sbin:$PATH"
        - curl https://getcomposer.org/installer | php

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then xvfb-run make tests; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make tests; fi
