language: php

php:
  - 7.1
# Below is all commented out because cannot be built atm
#  - 7.2
#  - nightly

#matrix:
#  allow_failures:
#    - php:
#      - 7.2
#      - nightly

addons:
  apt:
    packages:
      - libgtk-3-dev

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - ./travis/install-ui.sh
  - xvfb-run make vendor/autoload.php

matrix:
  include:
    - os: osx
      language: generic
      addons: skip
      before_install:
        - brew tap homebrew/php
        - brew update
        - brew install php71
        - curl https://getcomposer.org/installer | php

script: xvfb-run make tests
