language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php:
      - nightly
      - 7.2

addons:
  apt:
    packages:
      - xvfb
      - libgtk-3-dev

cache:
  directories:
    - $HOME/.composer/cache/files

stages:
  - test
  - code style

jobs:
  include:
    - stage: code style
      php: 7.1
      install: composer install --ignore-platform-reqs
      addons: skip
      script: vendor/bin/php-cs-fixer fix --using-cache=no --verbose --dry-run

install:
  - ./travis/install-ui.sh
  - xvfb-run make vendor/autoload.php
